### ISSUE TITLE
Encoders need to work more slowly

### ISSUE THREAD

**Issue by SetField** [synthetiv/euclidigons#1]
Some notes aren't accessible because encoders seem to be skipping some values

**Comment by synthetiv** [comment]
I've tweaked the sensitivity in a way that feels pretty good to me, and the missing notes should be fixed too -- the latest version defaults to an 8-note C minor scale and gives you the option to choose others in the params. Scale choices are the same as Awake's.

**Comment by synthetiv** [comment]
closing, but lemme know if something's still wrong --
