### ISSUE TITLE
Note/Octave Parameter Change

### ISSUE THREAD

**Issue by SetField** [synthetiv/euclidigons#10]
Do not make octave or note change active until K1 is released. This would allow for changing one or more note parameters simultaneously. More "playable" this way?

**Comment by synthetiv** [comment]
this would be useful! I also like being able to sort-of-arpeggiate by changing the note of a shape that's being struck regularly, but maybe once I implement this I won't want to go back, like the strike direction feature.

**Comment by synthetiv** [comment]
potential solution in the 'keys' branch: https://github.com/synthetiv/euclidigons/archive/keys.zip

**Comment by synthetiv** [comment]
Closing now that 'keys' has been merged into main :boom:
