### ISSUE TITLE
Strike triggering options

### ISSUE THREAD

**Issue by SetField** [synthetiv/euclidigons#4]
When I envisioned this script I didn't think about the intersections triggering notes when crossing out of the polygons as well as into them. The result is a doubling of hits which makes for more complex polyrhythms. I'm wondering if you could add an option to trigger just on entry (or just on exit). Thoughts?

**Comment by synthetiv** [comment]
I've had this thought too -- definitely worth trying out. And I'm still into the idea of a 'bow' triggering option too (play sustained notes while sides cross, not just at the moment a vertex strikes a side), which wouldn't double-trigger either.

**Comment by SetField** [comment]
Love that idea!

**Comment by synthetiv** [comment]
Turns out the 'pluck direction' is pretty easy to calculate _kind of_ accurately, but quite a bit trickier to calculate _very_ accurately, especially when the shape being plucked is moving quickly. Still pondering this one, probably gotta throw some calculus at it.

**Comment by synthetiv** [comment]
got this working in the 'engine' branch, and now as a bonus, it's velocity-sensitive. Thanks, calculus!

**Comment by synthetiv** [comment]
Oh right. This is done.
