### ISSUE TITLE
Polygon Selection When Stacked

### ISSUE THREAD

**Issue by SetField** [synthetiv/euclidigons#5]
When two or more polygons are centered on each other E1 can’t change the selection. I suppose you’re moving through them from L>R or R>L. Stacking order doesn’t exist.

**Comment by synthetiv** [comment]
Yep. No fun. Gotta make `get_next_shape()` handle a distance of 0. Might be slightly more complicated than changing a `>` to `>=`, but only slightly.

**Comment by synthetiv** [comment]
there are nice regular rhythms to be had from stacking polygons, so it may be worth adding some kind of feature to make it less visually confusing as well... not sure what that'd be yet.

**Comment by synthetiv** [comment]
:boom: selection order is now determined by x position, followed by shape size, followed by the order in which the shapes were created -- so there should never be a situation in which you can't select a particular shape.
